"""Semantic OPC UA information model for MHMC-01.

The PLC should stay free of hard-coded transport details.  This module is the
shared contract between the OPC UA runtime, SCADA collector configuration, and
the IEC 61131-3 symbolic variables exposed by ``Main``.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Iterable


NAMESPACE_URI = "http://antigravity.automation.org/MHMC/"
APPLICATION_URI = "urn:antigravity:automation:mhmc:opcua-server"


class NodeAccess(str, Enum):
    READ_ONLY = "RO"
    READ_WRITE = "RW"


@dataclass(frozen=True)
class NodeSpec:
    """One semantic variable in the MHMC OPC UA namespace."""

    node_id: str
    browse_name: str
    path: tuple[str, ...]
    variant_type: str
    default: Any
    access: NodeAccess
    description: str
    plc_symbol: str
    category: str
    historian_measurement: str
    historian_field: str
    engineering_unit: str = ""

    @property
    def is_writable(self) -> bool:
        return self.access == NodeAccess.READ_WRITE


OBJECT_PATHS: tuple[tuple[str, ...], ...] = (
    ("MHMC_Cell",),
    ("MHMC_Cell", "DeviceSet"),
    ("MHMC_Cell", "DeviceSet", "Conveyor_1"),
    ("MHMC_Cell", "DeviceSet", "Diverter_1"),
    ("MHMC_Cell", "DeviceSet", "Diverter_2"),
    ("MHMC_Cell", "DeviceSet", "Scanner_1"),
    ("MHMC_Cell", "ControlState"),
    ("MHMC_Cell", "KPIs"),
    ("MHMC_Cell", "Alarms"),
    ("MHMC_Cell", "Maintenance"),
    ("MHMC_Cell", "Recipes"),
    ("MHMC_Cell", "EventTimeline"),
    ("MHMC_Cell", "PLCIntegration"),
    ("MHMC_Cell", "Methods"),
)


NODE_SPECS: tuple[NodeSpec, ...] = (
    # Conveyor semantic object.
    NodeSpec(
        "DeviceSet.Conveyor_1.SpeedFeedback",
        "SpeedFeedback",
        ("MHMC_Cell", "DeviceSet", "Conveyor_1"),
        "Double",
        0.0,
        NodeAccess.READ_ONLY,
        "Actual conveyor velocity reported by the VFD feedback model.",
        "Main.fbConveyor.stStatus.rSpeedFeedback",
        "machine",
        "conveyor_telemetry",
        "speed_feedback",
        "m/s",
    ),
    NodeSpec(
        "DeviceSet.Conveyor_1.SpeedSetpoint",
        "SpeedSetpoint",
        ("MHMC_Cell", "DeviceSet", "Conveyor_1"),
        "Double",
        0.5,
        NodeAccess.READ_WRITE,
        "Requested conveyor velocity. In AUTO this maps to recipe speed trim.",
        "Main.rRecipeSpeed_mps",
        "machine",
        "conveyor_telemetry",
        "speed_setpoint",
        "m/s",
    ),
    NodeSpec(
        "DeviceSet.Conveyor_1.IsRunning",
        "IsRunning",
        ("MHMC_Cell", "DeviceSet", "Conveyor_1"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "True when the conveyor VFD run command is active and not quick-stopped.",
        "Main.xVfdRunCmd",
        "machine",
        "conveyor_telemetry",
        "is_running",
    ),
    NodeSpec(
        "DeviceSet.Conveyor_1.PE1_Blocked",
        "PE1_Blocked",
        ("MHMC_Cell", "DeviceSet", "Conveyor_1"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Infeed package photoelectric sensor after debounce.",
        "Main.xPE1Debounced",
        "machine",
        "conveyor_telemetry",
        "pe1_blocked",
    ),
    NodeSpec(
        "DeviceSet.Conveyor_1.PE2_Blocked",
        "PE2_Blocked",
        ("MHMC_Cell", "DeviceSet", "Conveyor_1"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Scanner trigger photoelectric sensor after debounce.",
        "Main.xPE2Debounced",
        "machine",
        "conveyor_telemetry",
        "pe2_blocked",
    ),
    NodeSpec(
        "DeviceSet.Conveyor_1.PE3_Blocked",
        "PE3_Blocked",
        ("MHMC_Cell", "DeviceSet", "Conveyor_1"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Diverter approach photoelectric sensor after debounce.",
        "Main.xPE3Debounced",
        "machine",
        "conveyor_telemetry",
        "pe3_blocked",
    ),
    NodeSpec(
        "DeviceSet.Conveyor_1.VFD_Current",
        "VFD_Current",
        ("MHMC_Cell", "DeviceSet", "Conveyor_1"),
        "Double",
        0.0,
        NodeAccess.READ_ONLY,
        "Conveyor VFD motor current diagnostic.",
        "Main.fbConveyor.stStatus.rCurrent",
        "machine",
        "conveyor_telemetry",
        "motor_current",
        "A",
    ),
    NodeSpec(
        "DeviceSet.Conveyor_1.Faulted",
        "Faulted",
        ("MHMC_Cell", "DeviceSet", "Conveyor_1"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Conveyor VFD fault or conveyor-local jam watchdog.",
        "Main.fbConveyor.stStatus.xFaulted",
        "alarm",
        "conveyor_telemetry",
        "faulted",
    ),
    # Diverter semantic objects.
    NodeSpec(
        "DeviceSet.Diverter_1.Home",
        "Home",
        ("MHMC_Cell", "DeviceSet", "Diverter_1"),
        "Boolean",
        True,
        NodeAccess.READ_ONLY,
        "Lane A diverter home/retracted switch.",
        "Main.stDiverter1Status.xHomeSensor",
        "machine",
        "diverter_1_telemetry",
        "is_home",
    ),
    NodeSpec(
        "DeviceSet.Diverter_1.Work",
        "Work",
        ("MHMC_Cell", "DeviceSet", "Diverter_1"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Lane A diverter work/extended switch.",
        "Main.stDiverter1Status.xWorkSensor",
        "machine",
        "diverter_1_telemetry",
        "is_work",
    ),
    NodeSpec(
        "DeviceSet.Diverter_1.CommandExtend",
        "CommandExtend",
        ("MHMC_Cell", "DeviceSet", "Diverter_1"),
        "Boolean",
        False,
        NodeAccess.READ_WRITE,
        "Hold-to-run diagnostic extend command for Lane A diverter.",
        "Main.xManualDiverter1Extend",
        "maintenance",
        "diverter_1_telemetry",
        "command_extend",
    ),
    NodeSpec(
        "DeviceSet.Diverter_1.PE_Verify",
        "PE_Verify",
        ("MHMC_Cell", "DeviceSet", "Diverter_1"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Lane A verification photoelectric sensor.",
        "Main.xPE4Debounced",
        "machine",
        "diverter_1_telemetry",
        "pe_verify",
    ),
    NodeSpec(
        "DeviceSet.Diverter_1.Faulted",
        "Faulted",
        ("MHMC_Cell", "DeviceSet", "Diverter_1"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Lane A diverter pneumatic timeout or interlock fault.",
        "Main.stDiverter1Status.xFaulted",
        "alarm",
        "diverter_1_telemetry",
        "faulted",
    ),
    NodeSpec(
        "DeviceSet.Diverter_2.Home",
        "Home",
        ("MHMC_Cell", "DeviceSet", "Diverter_2"),
        "Boolean",
        True,
        NodeAccess.READ_ONLY,
        "Lane B diverter home/retracted switch.",
        "Main.stDiverter2Status.xHomeSensor",
        "machine",
        "diverter_2_telemetry",
        "is_home",
    ),
    NodeSpec(
        "DeviceSet.Diverter_2.Work",
        "Work",
        ("MHMC_Cell", "DeviceSet", "Diverter_2"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Lane B diverter work/extended switch.",
        "Main.stDiverter2Status.xWorkSensor",
        "machine",
        "diverter_2_telemetry",
        "is_work",
    ),
    NodeSpec(
        "DeviceSet.Diverter_2.CommandExtend",
        "CommandExtend",
        ("MHMC_Cell", "DeviceSet", "Diverter_2"),
        "Boolean",
        False,
        NodeAccess.READ_WRITE,
        "Hold-to-run diagnostic extend command for Lane B diverter.",
        "Main.xManualDiverter2Extend",
        "maintenance",
        "diverter_2_telemetry",
        "command_extend",
    ),
    NodeSpec(
        "DeviceSet.Diverter_2.PE_Verify",
        "PE_Verify",
        ("MHMC_Cell", "DeviceSet", "Diverter_2"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Lane B verification photoelectric sensor.",
        "Main.xPE5Debounced",
        "machine",
        "diverter_2_telemetry",
        "pe_verify",
    ),
    NodeSpec(
        "DeviceSet.Diverter_2.Faulted",
        "Faulted",
        ("MHMC_Cell", "DeviceSet", "Diverter_2"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Lane B diverter pneumatic timeout or interlock fault.",
        "Main.stDiverter2Status.xFaulted",
        "alarm",
        "diverter_2_telemetry",
        "faulted",
    ),
    # Scanner.
    NodeSpec(
        "DeviceSet.Scanner_1.LastReadBarcode",
        "LastReadBarcode",
        ("MHMC_Cell", "DeviceSet", "Scanner_1"),
        "String",
        "",
        NodeAccess.READ_ONLY,
        "Most recent decoded barcode associated with the tracking FIFO.",
        "Main.sScannerData",
        "machine",
        "sorting_events",
        "last_barcode",
    ),
    NodeSpec(
        "DeviceSet.Scanner_1.Trigger",
        "Trigger",
        ("MHMC_Cell", "DeviceSet", "Scanner_1"),
        "Boolean",
        False,
        NodeAccess.READ_WRITE,
        "Diagnostic scanner trigger override, gated by PLC mode safeguards.",
        "Main.xManualScannerTrigger",
        "maintenance",
        "sorting_events",
        "manual_trigger",
    ),
    NodeSpec(
        "DeviceSet.Scanner_1.ReadSuccess",
        "ReadSuccess",
        ("MHMC_Cell", "DeviceSet", "Scanner_1"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "True when the last scanner payload was valid for routing.",
        "Main.xScannerDataValid",
        "machine",
        "sorting_events",
        "read_success",
    ),
    # Control state.
    NodeSpec(
        "ControlState.CurrentMode",
        "CurrentMode",
        ("MHMC_Cell", "ControlState"),
        "Int32",
        1,
        NodeAccess.READ_WRITE,
        "Current PackML mode: 0 MANUAL, 1 AUTO, 2 MAINTENANCE.",
        "Main.eSelectedMode",
        "state",
        "cell_state",
        "packml_mode",
    ),
    NodeSpec(
        "ControlState.CurrentState",
        "CurrentState",
        ("MHMC_Cell", "ControlState"),
        "Int32",
        9,
        NodeAccess.READ_ONLY,
        "Current PackML state: STOPPED, STARTING, EXECUTE, HELD, etc.",
        "Main.fbStationController.stOut.ePackMLState",
        "state",
        "cell_state",
        "packml_state",
    ),
    NodeSpec(
        "ControlState.PermissivesOK",
        "PermissivesOK",
        ("MHMC_Cell", "ControlState"),
        "Boolean",
        True,
        NodeAccess.READ_ONLY,
        "Aggregate safety, air, VFD, and diverter permissive status.",
        "Main.xPermissivesOK",
        "state",
        "cell_state",
        "permissives_ok",
    ),
    NodeSpec(
        "ControlState.Heartbeat",
        "Heartbeat",
        ("MHMC_Cell", "ControlState"),
        "UInt16",
        0,
        NodeAccess.READ_ONLY,
        "Cyclic PLC watchdog counter for collector freshness checks.",
        "Main.uiHeartbeat",
        "state",
        "cell_state",
        "heartbeat",
    ),
    # KPIs.
    NodeSpec(
        "KPIs.ThroughputTotal",
        "ThroughputTotal",
        ("MHMC_Cell", "KPIs"),
        "UInt32",
        0,
        NodeAccess.READ_ONLY,
        "Total verified packages processed by the cell.",
        "Main.fbKPIService.stOut.udiTotalPackages",
        "kpi",
        "cell_kpis",
        "throughput_total",
    ),
    NodeSpec(
        "KPIs.ThroughputLaneA",
        "ThroughputLaneA",
        ("MHMC_Cell", "KPIs"),
        "UInt32",
        0,
        NodeAccess.READ_ONLY,
        "Verified packages routed to Lane A.",
        "Main.fbKPIService.stOut.udiLaneAPackages",
        "kpi",
        "cell_kpis",
        "throughput_lane_a",
    ),
    NodeSpec(
        "KPIs.ThroughputLaneB",
        "ThroughputLaneB",
        ("MHMC_Cell", "KPIs"),
        "UInt32",
        0,
        NodeAccess.READ_ONLY,
        "Verified packages routed to Lane B.",
        "Main.fbKPIService.stOut.udiLaneBPackages",
        "kpi",
        "cell_kpis",
        "throughput_lane_b",
    ),
    NodeSpec(
        "KPIs.ThroughputReject",
        "ThroughputReject",
        ("MHMC_Cell", "KPIs"),
        "UInt32",
        0,
        NodeAccess.READ_ONLY,
        "Verified packages routed to reject.",
        "Main.fbKPIService.stOut.udiRejectPackages",
        "kpi",
        "cell_kpis",
        "throughput_reject",
    ),
    NodeSpec(
        "KPIs.TotalJams",
        "TotalJams",
        ("MHMC_Cell", "KPIs"),
        "UInt16",
        0,
        NodeAccess.READ_ONLY,
        "Cumulative jam events detected by the PLC watchdogs.",
        "Main.uiJamEventCounter",
        "kpi",
        "cell_kpis",
        "total_jams",
    ),
    NodeSpec(
        "KPIs.Availability",
        "Availability",
        ("MHMC_Cell", "KPIs"),
        "Double",
        1.0,
        NodeAccess.READ_ONLY,
        "OEE availability factor, 0.0 to 1.0.",
        "Main.rAvailability",
        "kpi",
        "cell_kpis",
        "availability",
    ),
    NodeSpec(
        "KPIs.Performance",
        "Performance",
        ("MHMC_Cell", "KPIs"),
        "Double",
        0.96,
        NodeAccess.READ_ONLY,
        "OEE performance factor, 0.0 to 1.0.",
        "Main.rPerformance",
        "kpi",
        "cell_kpis",
        "performance",
    ),
    NodeSpec(
        "KPIs.Quality",
        "Quality",
        ("MHMC_Cell", "KPIs"),
        "Double",
        1.0,
        NodeAccess.READ_ONLY,
        "OEE quality factor, 0.0 to 1.0.",
        "Main.rQuality",
        "kpi",
        "cell_kpis",
        "quality",
    ),
    NodeSpec(
        "KPIs.OEE",
        "OEE",
        ("MHMC_Cell", "KPIs"),
        "Double",
        100.0,
        NodeAccess.READ_ONLY,
        "Overall Equipment Effectiveness percentage.",
        "Main.rOEEPercentage",
        "kpi",
        "cell_kpis",
        "oee",
        "%",
    ),
    # Alarm and event state.
    NodeSpec(
        "Alarms.AnyActive",
        "AnyActive",
        ("MHMC_Cell", "Alarms"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "True when any alarm condition is active.",
        "Main.fbAlarmManager.stOut.xAnyAlarmActive",
        "alarm",
        "alarms_events",
        "any_active",
    ),
    NodeSpec(
        "Alarms.AnyUnacked",
        "AnyUnacked",
        ("MHMC_Cell", "Alarms"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "True when an active alarm has not been acknowledged.",
        "Main.fbAlarmManager.stOut.xAnyUnacked",
        "alarm",
        "alarms_events",
        "any_unacked",
    ),
    NodeSpec(
        "Alarms.ActiveCode",
        "ActiveCode",
        ("MHMC_Cell", "Alarms"),
        "UInt16",
        0,
        NodeAccess.READ_ONLY,
        "Current alarm code aligned with E_MHMCAlarmCode.",
        "Main.fbAlarmManager.stOut.uiActiveAlarmCode",
        "alarm",
        "alarms_events",
        "active_code",
    ),
    NodeSpec(
        "Alarms.Severity",
        "Severity",
        ("MHMC_Cell", "Alarms"),
        "UInt16",
        0,
        NodeAccess.READ_ONLY,
        "OPC UA severity value, 0 to 1000.",
        "Main.fbAlarmManager.stOut.uiSeverity",
        "alarm",
        "alarms_events",
        "severity",
    ),
    NodeSpec(
        "Alarms.ActiveMessage",
        "ActiveMessage",
        ("MHMC_Cell", "Alarms"),
        "String",
        "No active alarms",
        NodeAccess.READ_ONLY,
        "Operator-ready active alarm text.",
        "Main.fbAlarmManager.stOut.sActiveMessage",
        "alarm",
        "alarms_events",
        "active_message",
    ),
    NodeSpec(
        "Alarms.GeneralJamAlarm",
        "GeneralJamAlarm",
        ("MHMC_Cell", "Alarms"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Package jam condition detected by conveyor or jam detector.",
        "Main.fbAlarmManager.stOut.xGeneralJamAlarm",
        "alarm",
        "alarms_events",
        "general_jam_alarm",
    ),
    NodeSpec(
        "Alarms.Diverter1Fault",
        "Diverter1Fault",
        ("MHMC_Cell", "Alarms"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Lane A pneumatic diverter fault.",
        "Main.fbAlarmManager.stOut.xDiverter1Alarm",
        "alarm",
        "alarms_events",
        "diverter_1_fault",
    ),
    NodeSpec(
        "Alarms.Diverter2Fault",
        "Diverter2Fault",
        ("MHMC_Cell", "Alarms"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Lane B pneumatic diverter fault.",
        "Main.fbAlarmManager.stOut.xDiverter2Alarm",
        "alarm",
        "alarms_events",
        "diverter_2_fault",
    ),
    NodeSpec(
        "Alarms.EStopTripped",
        "EStopTripped",
        ("MHMC_Cell", "Alarms"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "Emergency stop or safety loop opened.",
        "Main.fbAlarmManager.stOut.xEStopAlarm",
        "alarm",
        "alarms_events",
        "estop_tripped",
    ),
    NodeSpec(
        "Alarms.Acknowledge",
        "Acknowledge",
        ("MHMC_Cell", "Alarms"),
        "Boolean",
        False,
        NodeAccess.READ_WRITE,
        "One-shot alarm acknowledge command from HMI or SCADA.",
        "Main.xAlarmAcknowledge",
        "alarm",
        "alarms_events",
        "acknowledge_command",
    ),
    # Maintenance and engineering controls.
    NodeSpec(
        "Maintenance.ManualJogForward",
        "ManualJogForward",
        ("MHMC_Cell", "Maintenance"),
        "Boolean",
        False,
        NodeAccess.READ_WRITE,
        "Hold-to-run conveyor jog command, mode-gated by PLC logic.",
        "Main.xManualJogForward",
        "maintenance",
        "maintenance",
        "manual_jog_forward",
    ),
    NodeSpec(
        "Maintenance.ManualJogSpeed",
        "ManualJogSpeed",
        ("MHMC_Cell", "Maintenance"),
        "Double",
        0.2,
        NodeAccess.READ_WRITE,
        "Requested manual/maintenance jog speed before PLC clamps.",
        "Main.rManualJogSpeed_mps",
        "maintenance",
        "maintenance",
        "manual_jog_speed",
        "m/s",
    ),
    NodeSpec(
        "Maintenance.MaintenanceKey",
        "MaintenanceKey",
        ("MHMC_Cell", "Maintenance"),
        "Boolean",
        False,
        NodeAccess.READ_WRITE,
        "Engineering key or role grant required for maintenance mode.",
        "Main.xMaintenanceKey",
        "maintenance",
        "maintenance",
        "maintenance_key",
    ),
    NodeSpec(
        "Maintenance.ResetCounters",
        "ResetCounters",
        ("MHMC_Cell", "Maintenance"),
        "Boolean",
        False,
        NodeAccess.READ_WRITE,
        "Maintenance KPI counter reset command.",
        "Main.xManualResetCounters",
        "maintenance",
        "maintenance",
        "reset_counters",
    ),
    # Recipe command surface.
    NodeSpec(
        "Recipes.ActiveRecipeID",
        "ActiveRecipeID",
        ("MHMC_Cell", "Recipes"),
        "UInt16",
        1,
        NodeAccess.READ_WRITE,
        "Selected recipe ID for LoadRecipe command.",
        "Main.uiRecipeSelect",
        "recipe",
        "recipes",
        "active_recipe_id",
    ),
    NodeSpec(
        "Recipes.ActiveRecipeName",
        "ActiveRecipeName",
        ("MHMC_Cell", "Recipes"),
        "String",
        "Default Lane A",
        NodeAccess.READ_ONLY,
        "Operator-facing active recipe name.",
        "Main.fbLineSupervisor.stOut.stActiveRecipe.sName",
        "recipe",
        "recipes",
        "active_recipe_name",
    ),
    NodeSpec(
        "Recipes.TargetSpeed",
        "TargetSpeed",
        ("MHMC_Cell", "Recipes"),
        "Double",
        0.5,
        NodeAccess.READ_WRITE,
        "Requested recipe speed trim. Zero means use recipe default.",
        "Main.rRecipeSpeed_mps",
        "recipe",
        "recipes",
        "target_speed",
        "m/s",
    ),
    # Event timeline ring-buffer head.
    NodeSpec(
        "EventTimeline.NewEvent",
        "NewEvent",
        ("MHMC_Cell", "EventTimeline"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "One-scan pulse indicating the PLC event timeline appended a record.",
        "Main.stEventTimeline.xNewEvent",
        "event",
        "event_timeline",
        "new_event",
    ),
    NodeSpec(
        "EventTimeline.LastSequence",
        "LastSequence",
        ("MHMC_Cell", "EventTimeline"),
        "UInt32",
        0,
        NodeAccess.READ_ONLY,
        "Monotonic sequence number of the last PLC event.",
        "Main.stEventTimeline.stLastEvent.udiSequence",
        "event",
        "event_timeline",
        "last_sequence",
    ),
    NodeSpec(
        "EventTimeline.LastClass",
        "LastClass",
        ("MHMC_Cell", "EventTimeline"),
        "Int32",
        0,
        NodeAccess.READ_ONLY,
        "Event class aligned with E_MHMCEventClass.",
        "Main.stEventTimeline.stLastEvent.eClass",
        "event",
        "event_timeline",
        "last_class",
    ),
    NodeSpec(
        "EventTimeline.LastMessage",
        "LastMessage",
        ("MHMC_Cell", "EventTimeline"),
        "String",
        "",
        NodeAccess.READ_ONLY,
        "Message text of the last PLC event timeline record.",
        "Main.stEventTimeline.stLastEvent.sMessage",
        "event",
        "event_timeline",
        "last_message",
    ),
    NodeSpec(
        "EventTimeline.LastSeverity",
        "LastSeverity",
        ("MHMC_Cell", "EventTimeline"),
        "UInt16",
        0,
        NodeAccess.READ_ONLY,
        "Severity of the last PLC event timeline record.",
        "Main.stEventTimeline.stLastEvent.uiSeverity",
        "event",
        "event_timeline",
        "last_severity",
    ),
    # PLC historian/collector integration health.
    NodeSpec(
        "PLCIntegration.SubscribeEnable",
        "SubscribeEnable",
        ("MHMC_Cell", "PLCIntegration"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "PLC-side historian connector subscription enable.",
        "Main.fbHistorianConnector.stOut.xSubscribeEnable",
        "integration",
        "collector_health",
        "subscribe_enable",
    ),
    NodeSpec(
        "PLCIntegration.CollectorHeartbeat",
        "CollectorHeartbeat",
        ("MHMC_Cell", "PLCIntegration"),
        "Boolean",
        False,
        NodeAccess.READ_WRITE,
        "Collector heartbeat bit written by SCADA/OPC UA bridge.",
        "Main.xCollectorHeartbeat",
        "integration",
        "collector_health",
        "collector_heartbeat",
    ),
    NodeSpec(
        "PLCIntegration.HistorianHealthy",
        "HistorianHealthy",
        ("MHMC_Cell", "PLCIntegration"),
        "Boolean",
        False,
        NodeAccess.READ_ONLY,
        "PLC-side view of collector health and heartbeat freshness.",
        "Main.fbHistorianConnector.stOut.xHistorianHealthy",
        "integration",
        "collector_health",
        "historian_healthy",
    ),
)


def nodes_by_id() -> dict[str, NodeSpec]:
    return {spec.node_id: spec for spec in NODE_SPECS}


def specs_for_category(category: str) -> tuple[NodeSpec, ...]:
    return tuple(spec for spec in NODE_SPECS if spec.category == category)


def default_values() -> dict[str, Any]:
    return {spec.node_id: spec.default for spec in NODE_SPECS}


def plc_mapping_rows(specs: Iterable[NodeSpec] = NODE_SPECS) -> list[dict[str, str]]:
    """Return a serializable mapping table for audits and fieldbus binding."""

    return [
        {
            "node_id": spec.node_id,
            "browse_name": spec.browse_name,
            "access": spec.access.value,
            "data_type": spec.variant_type,
            "plc_symbol": spec.plc_symbol,
            "measurement": spec.historian_measurement,
            "field": spec.historian_field,
            "description": spec.description,
        }
        for spec in specs
    ]


REQUIRED_NODE_IDS = frozenset(
    {
        "DeviceSet.Conveyor_1.SpeedFeedback",
        "DeviceSet.Conveyor_1.SpeedSetpoint",
        "DeviceSet.Conveyor_1.IsRunning",
        "DeviceSet.Conveyor_1.PE1_Blocked",
        "DeviceSet.Conveyor_1.PE2_Blocked",
        "DeviceSet.Conveyor_1.PE3_Blocked",
        "DeviceSet.Diverter_1.Home",
        "DeviceSet.Diverter_1.Work",
        "DeviceSet.Diverter_1.CommandExtend",
        "DeviceSet.Diverter_2.Home",
        "DeviceSet.Diverter_2.Work",
        "DeviceSet.Diverter_2.CommandExtend",
        "DeviceSet.Scanner_1.LastReadBarcode",
        "DeviceSet.Scanner_1.Trigger",
        "DeviceSet.Scanner_1.ReadSuccess",
        "ControlState.CurrentMode",
        "ControlState.CurrentState",
        "ControlState.PermissivesOK",
        "ControlState.Heartbeat",
        "KPIs.ThroughputTotal",
        "KPIs.ThroughputLaneA",
        "KPIs.ThroughputLaneB",
        "KPIs.ThroughputReject",
        "KPIs.TotalJams",
        "KPIs.OEE",
        "Alarms.GeneralJamAlarm",
        "Alarms.Diverter1Fault",
        "Alarms.Diverter2Fault",
        "Alarms.EStopTripped",
        "Maintenance.MaintenanceKey",
        "Maintenance.ManualJogSpeed",
        "EventTimeline.LastSequence",
        "PLCIntegration.SubscribeEnable",
    }
)
