# Build helper for TwinCAT projects in this workspace.
#
# Usage:
#   .\tools\build-twincat.ps1
#   .\tools\build-twincat.ps1 -SolutionPath .\TwinCAT\MHMC.sln

[CmdletBinding()]
param(
    [string]$SolutionPath = "",
    [string]$Configuration = "Release",
    [string]$Platform = "TwinCAT RT (x64)"
)

$ErrorActionPreference = "Stop"

$workspace = Resolve-Path (Join-Path $PSScriptRoot "..")
. (Join-Path $PSScriptRoot "twincat-env.ps1")

if ([string]::IsNullOrWhiteSpace($SolutionPath)) {
    $generator = Join-Path $PSScriptRoot "generate-twincat-project.ps1"
    if (Test-Path -LiteralPath $generator) {
        Write-Host "Regenerating TwinCAT build container from plc/*.st..."
        & powershell -NoProfile -ExecutionPolicy Bypass -File $generator | Out-Host
    }

    $solutions = Get-ChildItem -LiteralPath $workspace -Recurse -File |
        Where-Object {
            ($_.Extension -in @(".sln", ".tsproj")) -and
            ($_.FullName -notmatch "\\_Boot\\|\\bin\\|\\obj\\|\\.git\\")
        } |
        Sort-Object @{ Expression = { if ($_.Extension -eq ".sln") { 0 } else { 1 } } }, FullName |
        Select-Object -ExpandProperty FullName

    if ($solutions.Count -eq 0) {
        $plcProjects = Get-ChildItem -LiteralPath $workspace -Recurse -File |
            Where-Object {
                ($_.Extension -eq ".plcproj") -and
                ($_.FullName -notmatch "\\_Boot\\|\\bin\\|\\obj\\|\\.git\\")
            } |
            Select-Object -ExpandProperty FullName

        Write-Host "TwinCAT toolchain is available:" -ForegroundColor Green
        Get-TwinCATToolchain | Format-List
        Write-Host "No headless-buildable TwinCAT container was found in this workspace." -ForegroundColor Yellow
        Write-Host "Expected one of: .sln or .tsproj." -ForegroundColor Yellow
        if ($plcProjects.Count -gt 0) {
            Write-Host "PLC project wrapper(s) found, but .plcproj alone does not expose a command-line Build target:" -ForegroundColor Yellow
            $plcProjects | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
        }
        Write-Host "Current PLC source is loose IEC ST under: $workspace\plc" -ForegroundColor Yellow
        exit 2
    }

    $SolutionPath = $solutions | Select-Object -First 1
}

$resolvedSolution = Resolve-Path $SolutionPath
if ([System.IO.Path]::GetExtension($resolvedSolution) -eq ".plcproj") {
    Write-Host "TwinCAT toolchain is available:" -ForegroundColor Green
    Get-TwinCATToolchain | Format-List
    Write-Host ".plcproj was supplied, but this install cannot headless-build .plcproj directly." -ForegroundColor Yellow
    Write-Host "Use a .sln or .tsproj generated by TwinCAT XAE Shell for command-line build." -ForegroundColor Yellow
    exit 3
}

Write-Host "Using TwinCAT XAE Shell:" $env:TWINCAT_XAE_SHELL
Write-Host "Building:" $resolvedSolution

Invoke-TwinCATBuild -SolutionPath $resolvedSolution -Configuration $Configuration -Platform $Platform
